apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grade-submission-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kundan547/grade-api-gitops.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade-submission-api
  template:
    metadata:
      labels:
        app: grade-submission-api
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: grade-submission-api
        image: ghcr.io/kundan547/kubernetes-cicd-tutorial:5ca1f95cde9dc6de86ff32c43378b14aec766e71
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
  namespace: default
spec:
  selector:
    app: grade-submission-api
  ports:
  - port: 80
    targetPort: 3000
  type: NodePort
